using System.Text;

namespace AStarDev.SourceGenerators.OptionsBindingGeneration;

/// <summary>
///  The <see cref="OptionsBindingCodeGenerator" /> class is responsible for generating the source code for the <c>AddAutoRegisteredOptions</c> extension method, which registers all options classes annotated with the <see cref="AStarDev.SourceGeneratorAttributes.AutoRegisterOptionsAttribute" /> in the dependency injection container.
/// </summary>
internal static class OptionsBindingCodeGenerator
{
    /// <summary>
    ///   Generates the source code for the <c>AddAutoRegisteredOptions</c> extension method, which registers all options classes annotated with the <see cref="AStarDev.SourceGeneratorAttributes.AutoRegisterOptionsAttribute" /> in the dependency injection container.
    /// </summary>
    /// <param name="types">The list of options types to generate registration code for.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Generate(IReadOnlyList<OptionsTypeInfo> types)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine("using Microsoft.Extensions.Configuration;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("namespace AStarDev.SourceGenerators.OptionsBindingGeneration");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static class AutoOptionsRegistrationExtensions");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        public static IServiceCollection AddAutoRegisteredOptions(this IServiceCollection services, IConfiguration configuration)");
        _ = sb.AppendLine("        {");
        foreach (var info in types) _ = sb.AppendLine($"            services.AddOptions<{info.FullTypeName}>()\n                .Bind(configuration.GetSection(\"{EscapeString(info.SectionName)}\"))\n                .ValidateDataAnnotations()\n                .ValidateOnStart();");

        _ = sb.AppendLine("            return services;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeString(string s) => s?.Replace("\\", @"\\").Replace("\"", "\\\"") ?? string.Empty;
}
