<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="System.Reactive" />
    </ItemGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PackageTags>opentelemetry;extensions;astar;astardevelopment</PackageTags>
        <Title>AStar Dev Logging OpenTelemetry</Title>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <Description>An OpenTelemetry logging configuration for AStar Dev applications.</Description>
        <PackageProjectUrl>https://github.com/astar-development/astar-dev-mono/tree/main/packages/core</PackageProjectUrl>
        <DocumentationFile>$(AssemblyName).xml</DocumentationFile>
        <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <NoWarn>$(NoWarn);CA1724;CA1062</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
