<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);IDE1006</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../AStarDev.FunctionalParadigm/AStarDev.FunctionalParadigm.csproj" />
  </ItemGroup>
</Project>