<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <RootNamespace>AStarDev.SourceGenerators.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AStarDev.SourceGeneratorAttributes\AStarDev.SourceGeneratorAttributes.csproj" />
    </ItemGroup>

</Project>
