using System.Text;
using AStarDev.SourceGeneratorAttributes;

namespace AStarDev.SourceGenerators.ServiceRegistrationGeneration;

internal static class ServiceCollectionCodeGenerator
{
    public static string? Generate(IReadOnlyList<ServiceModel> items)
    {
        if (items.Count == 0)
            return null;

        var byLayer = GroupByLayer(items);
        var methods = BuildLayerMethods(byLayer).Append(BuildUmbrellaMethod(byLayer.Select(l => l.Layer)));

        return BuildSourceFile(methods, items[0]?.Namespace ?? "AStarDev");
    }

    private static List<(Layer Layer, string[] Registrations)> GroupByLayer(IReadOnlyList<ServiceModel> items)
    {
        var result = new List<(Layer, string[])>();

        foreach (Layer layer in Enum.GetValues(typeof(Layer)).Cast<Layer>())
        {
            var forLayer = items.Where(i => i is not null && i.Layer == layer).Select(i => i!).ToArray();
            var registrations = BuildServiceRegistrations(forLayer).ToArray();

            if (registrations.Length > 0)
                result.Add((layer, registrations));
        }

        return result;
    }

    private static IEnumerable<string> BuildLayerMethods(IEnumerable<(Layer Layer, string[] Registrations)> byLayer)
    {
        foreach (var (layer, registrations) in byLayer)
            yield return BuildMethod($"Add{layer}Services", registrations);
    }

    private static string BuildUmbrellaMethod(IEnumerable<Layer> layers)
        => BuildMethod("AddAnnotatedServices", layers.Select(layer => $"        services.Add{layer}Services();"));

    private static string BuildMethod(string name, IEnumerable<string> bodyLines)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine($"    public static IServiceCollection {name}(this IServiceCollection services)");
        _ = sb.AppendLine("    {");

        foreach (string line in bodyLines)
            _ = sb.AppendLine(line);

        _ = sb.AppendLine("        return services;");
        _ = sb.Append("    }");

        return sb.ToString();
    }

    private static IEnumerable<string> BuildServiceRegistrations(IReadOnlyList<ServiceModel> items)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var model in items)
            foreach (string? registration in CreateRegistrationsForModel(model).Where(seen.Add)) yield return registration;
    }

    private static IEnumerable<string> CreateRegistrationsForModel(ServiceModel model)
    {
        string method = GetRegistrationMethod(model.Lifetime);

        if (!string.IsNullOrEmpty(model.ServiceFqn))
        {
            yield return $"        services.{method}<{model.ServiceFqn}, {model.ImplFqn}>();";

            if (model.AlsoAsSelf)
                yield return $"        services.{method}<{model.ImplFqn}>();";
        }
        else
            yield return $"        services.{method}<{model.ImplFqn}>();";
    }

    private static string GetRegistrationMethod(ServiceLifetime lifetime)
        => lifetime switch
        {
            ServiceLifetime.Singleton => "AddSingleton",
            ServiceLifetime.Scoped => "AddScoped",
            ServiceLifetime.Transient => "AddTransient",
            _ => "AddScoped"
        };

    private static string BuildSourceFile(IEnumerable<string> methods, string @namespace)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {@namespace};");
        _ = sb.AppendLine();
        _ = sb.AppendLine("public static class GeneratedServiceCollectionExtensions");
        _ = sb.AppendLine("{");
        _ = sb.Append(string.Join("\n\n", methods));
        _ = sb.AppendLine();
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
