using System.Text;
using AStarDev.SourceGeneratorAttributes;

namespace AStarDev.SourceGenerators.ServiceRegistrationGeneration;

internal static class ServiceCollectionCodeGenerator
{
    public static string? Generate(IReadOnlyList<ServiceModel> items)
    {
        if (items.Count == 0)
            return null;

        var registrations = BuildServiceRegistrations(items);
        var item = items[0];

        return BuildSourceFile(registrations, item?.Namespace ?? "AStarDev");
    }

    private static IEnumerable<string> BuildServiceRegistrations(IReadOnlyList<ServiceModel> items)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var model in items)
            foreach (string? registration in CreateRegistrationsForModel(model).Where(seen.Add)) yield return registration;
    }

    private static IEnumerable<string> CreateRegistrationsForModel(ServiceModel model)
    {
        string method = GetRegistrationMethod(model.Lifetime);

        if (!string.IsNullOrEmpty(model.ServiceFqn))
        {
            yield return $"        services.{method}<{model.ServiceFqn}, {model.ImplFqn}>();";

            if (model.AlsoAsSelf)
                yield return $"        services.{method}<{model.ImplFqn}>();";
        }
        else
            yield return $"        services.{method}<{model.ImplFqn}>();";
    }

    private static string GetRegistrationMethod(ServiceLifetime lifetime)
        => lifetime switch
        {
            ServiceLifetime.Singleton => "AddSingleton",
            ServiceLifetime.Scoped => "AddScoped",
            ServiceLifetime.Transient => "AddTransient",
            _ => "AddScoped"
        };

    private static string BuildSourceFile(IEnumerable<string> registrations, string @namespace)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"namespace {@namespace};");
        _ = sb.AppendLine();
        _ = sb.AppendLine("public static class GeneratedServiceCollectionExtensions");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)");
        _ = sb.AppendLine("    {");

        foreach (string? registration in registrations)
            _ = sb.AppendLine(registration);

        _ = sb.AppendLine("        return services;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
