// <auto-generated />
using System;
using AStarDev.ControlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.ControlDb.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260904193436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScrapeConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseDirectoryFamous")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseSaveDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubDirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ScrapeDirectories", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFamous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPageVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("SearchConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("SearchConfigurationId");

                    b.ToTable("SearchCategoryEntity");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImagePauseInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScrapeConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SearchStringPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SearchStringSuffix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<float?>("SlowMotionDelay")
                        .HasColumnType("REAL");

                    b.Property<int>("StartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscriptions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SubscriptionsStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionsTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TopWallpapersStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopWallpapersTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseHeadless")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationId")
                        .IsUnique();

                    b.ToTable("SearchConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionCookie")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("UserConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("ScrapeDirectories")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchCategoryEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", "SearchConfiguration")
                        .WithMany("SearchCategories")
                        .HasForeignKey("SearchConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchConfiguration");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("SearchConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", "ScrapeConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("UserConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Navigation("ScrapeDirectories")
                        .IsRequired();

                    b.Navigation("SearchConfiguration")
                        .IsRequired();

                    b.Navigation("UserConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.Navigation("SearchCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
