// <auto-generated />
using System;
using System.Collections.Generic;
using AStarDev.ControlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.ControlDb.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260912191420_RemoveScrapeLevelPropertiesFromSearchConfiguration")]
    partial class RemoveScrapeLevelPropertiesFromSearchConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.DeletionStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HardDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HardDeletePending_Ticks");

                    b.Property<long?>("SoftDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeletePending_Ticks");

                    b.Property<long?>("SoftDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeleted_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("DeletionStatus", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.FileAccessDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DetailsLastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetailsLastUpdated_Ticks");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastViewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastViewed_Ticks");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("FileAccessDetail", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHandle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DirectoryName", "AStarDev.ControlDb.FileDetail.FileEntity.DirectoryName#DirectoryName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DirectoryName")
                                .UseCollation("NOCASE");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FileName", "AStarDev.ControlDb.FileDetail.FileEntity.FileName#FileName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("FileName")
                                .UseCollation("NOCASE");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FileHandle")
                        .IsUnique();

                    b.HasIndex("FileSize");

                    b.HasIndex("IsImage", "FileSize")
                        .HasDatabaseName("IX_FileDetail_DuplicateImages");

                    b.ToTable("FileDetail", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.ImageDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("ImageDetail", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImagePauseInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SearchStringPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("SearchStringSuffix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<float?>("SlowMotionDelay")
                        .HasColumnType("REAL");

                    b.Property<int>("StartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscriptions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("SubscriptionsStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionsTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TopWallpapersStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopWallpapersTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseHeadless")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScrapeConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("RootDirectoryFamous")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubDirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ScrapeDirectories", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchCategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFamous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPageVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("SearchConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("SearchConfigurationId");

                    b.ToTable("SearchCategoryEntity");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScrapeConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationId")
                        .IsUnique();

                    b.ToTable("SearchConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("UserConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.TagDetail.FileTagEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FileTags", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.TagDetail.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Purity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("WallhavenTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WallhavenTagId")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.DeletionStatusEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.FileDetail.FileEntity", "FileDetail")
                        .WithOne("DeletionStatus")
                        .HasForeignKey("AStarDev.ControlDb.FileDetail.DeletionStatusEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.FileAccessDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.FileDetail.FileEntity", "FileDetail")
                        .WithOne("FileAccessDetail")
                        .HasForeignKey("AStarDev.ControlDb.FileDetail.FileAccessDetailEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.ImageDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.FileDetail.FileEntity", "FileDetail")
                        .WithOne("ImageDetail")
                        .HasForeignKey("AStarDev.ControlDb.FileDetail.ImageDetailEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("ScrapeDirectories")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchCategoryEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", "SearchConfiguration")
                        .WithMany("SearchCategories")
                        .HasForeignKey("SearchConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchConfiguration");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("SearchConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", "ScrapeConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("UserConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.TagDetail.FileTagEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.FileDetail.FileEntity", "FileDetail")
                        .WithMany("FileTags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStarDev.ControlDb.TagDetail.TagEntity", "Tag")
                        .WithMany("FileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileDetail");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AStarDev.ControlDb.FileDetail.FileEntity", b =>
                {
                    b.Navigation("DeletionStatus");

                    b.Navigation("FileAccessDetail")
                        .IsRequired();

                    b.Navigation("FileTags");

                    b.Navigation("ImageDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Navigation("ScrapeDirectories")
                        .IsRequired();

                    b.Navigation("SearchConfiguration")
                        .IsRequired();

                    b.Navigation("UserConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.Navigation("SearchCategories");
                });

            modelBuilder.Entity("AStarDev.ControlDb.TagDetail.TagEntity", b =>
                {
                    b.Navigation("FileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
